name: ci
on:
  push:
    branches:
      - "main"
  workflow_dispatch:
env:
  IMAGE_NAME: django-website
  GITHUB_USERNAME: pinkesh-ceq
  GITHUB_EMAIL: "pinkesh@cloudeq.com"
  GITHUB_REPO_NAME_K8S: django-website-kubernates-config

jobs:
  Docker_build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Output Run Number
        run: echo ${{ github.run_number }}
      
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.run_number }}

  update_deployment_manifest:
    runs-on: ubuntu-latest
    needs: ['Docker_build_and_push']
    steps:
      - name: Output Run Number
        run: echo ${{ github.run_number }}
      - name: Checkout
        uses: actions/checkout@v3
        with: 
          repository: ${{ env.GITHUB_USERNAME }}/${{ env.GITHUB_REPO_NAME_K8S }}
          ref: 'master'
          token: ${{ secrets.K8S_GITHUB_TOKEN }}
      - name: setup git config
        run: |
          git config --global user.name "${{ env.GITHUB_USERNAME }}"
          git config --global user.email "${{ env.GITHUB_EMAIL }}"
          # sed -i "s#${{ github.actor }}.*#${{ github.actor }}/${{ env.IMAGE_NAME }}:${{ github.run_number }}"
          sh "sed -i 's+${{ env.GITHUB_USERNAME }}/${{ env.IMAGE_NAME }}.*+${{ env.GITHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.run_number }}+g' deployment.yaml"
          git add -A
          git commit -m "Updated website version: ${{ github.run_number }}"
          git push origin master