name: ci
on:
  push:
    branches:
      - "main"
  workflow_dispatch:
env:
  IMAGE_NAME: django-website
  DOCKERHUB_USERNAME: pinkeshceq
  GITHUB_USERNAME: pinkesh-ceq
  GITHUB_EMAIL: pinkesh@cloudeq.com
  GITHUB_REPO_NAME_K8S: django-website-kubernates-config
  DEPLOYMENT_FILE: deployment.yml
  ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
  ECR_REPOSITORY: ceq-wp
  IMAGE_TAG: ${{ github.run_number }}

jobs:
  Docker_build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Output Run Number
        run: echo ${{ github.run_number }}
      
      -
        name: Checkout
        uses: actions/checkout@v3

      - 
        name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws-region: ap-south-1
      -
        name: Login to Amazon ECR 
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      -
        name: Build the Docker image and Push into Amazon ECR
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG --build-arg db_host=${{secrets.DB_HOST}} --build-arg db_user=${{secrets.DB_USER}} --build-arg db_password=${{secrets.DB_PASSWORD}} --build-arg db_name=${{secrets.DB_NAME}} . --file Dockerfile
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
    

  update_deployment_manifest:
    runs-on: ubuntu-latest
    needs: ['Docker_build_and_push']
    steps:
      - name: Output Run Number
        run: echo ${{ github.run_number }}
      - name: Checkout
        uses: actions/checkout@v3
        with: 
          repository: ${{ env.GITHUB_USERNAME }}/${{ env.GITHUB_REPO_NAME_K8S }}
          ref: 'main'
          token: ${{ secrets.K8S_GITHUB_TOKEN }}
      - name: setup git config
        run: |
          git config --global user.name "${{ env.GITHUB_USERNAME }}"
          git config --global user.email "${{ env.GITHUB_EMAIL }}"
          sed -i "s#${{ env.ECR_REGISTRY:}}.*#${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}#g" ${{ env.DEPLOYMENT_FILE }}
          git add -A
          git commit -m "Updated website version: ${{ github.run_number }}"
          git push origin master
